CREATE TABLE NhanVien (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    MaNV NVARCHAR(50) NOT NULL,
    HoTen NVARCHAR(100) NOT NULL,
    SDT NVARCHAR(20),
    CCCD NVARCHAR(20),
    Email NVARCHAR(100),
    DiaChi NVARCHAR(255),
    PhongBan NVARCHAR(100),
    ChucVu NVARCHAR(100),
    CreatedDate DATETIME DEFAULT GETDATE()
);